version: '3.0'

services:

  merchant:
    build: ./
    container_name: go_merchant
    command: go run ./main.go
    restart: unless-stopped
    ports:
      - "8091:8091"
    depends_on:
      - dynamodb
    networks:
      - service

  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8042:8000"

networks:
  service: