version: '3.0'

services:
  merchant:
    build: ./
    container_name: go_merchant
    ports:
      - "8091:8091"
    depends_on:
      - dynamodb
    environment:
      - AWS_DEFAULT_REGION=local
      - AWS_ACCESS_KEY_ID=1
      - AWS_SECRET_ACCESS_KEY=1
    command:  sh -c 'sh /go/src/app/init-scripts/populate.sh && go run /go/src/app/cmd/main.go'
    networks:
     service:
       ipv4_address: 172.19.0.3

  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8042:8000"
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory" ]
    networks:
      service:
        ipv4_address: 172.19.0.2

networks:
  service:
    external: true