app:
  aws:
    dynamo:
      region: local
      endpoint: http://127.0.0.1:8042
      tables:
        users: users
      httpClient:
        connectionTimeout: 10s

  server:
    port: :8091
    shutdownTimeout: 20s