app:
  aws:
    dynamo:
      region: local
      endpoint: http://172.19.0.2:8000
      tables:
        users: users
      httpClient:
        connectionTimeout: 10s

  server:
    port: :8091
    shutdownTimeout: 20s