info:
  title: Ebook Merchant
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
swagger: '2.0'
securityDefinitions:
  keystone:
    description: OpenStack Keystone Authentication
    type: apiKey
    in: header
    name: x-auth-token

paths:
  /api/register/:
    post:
      operationId: CreateUser
      summary: Create new user
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Register'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Register'

definitions:
  Register:
    type: object
    properties:
      username:
        description: Name of the new user
        type: string
      firstname:
        description: First name of user
        type: string
      surname:
        description: Surname of the user
        type: string
      email:
        description: Email of the user
        type: string
      phoneNumber:
        description: User phone number
        type: string
